data_config:
  batch_size: 64
  boundary: true
  data_path: data/rijke_kings_beta_5_7_tau_0_2.h5
  data_type: rijke
  dt: 0.01
  interp_val_split: 0.2
  interp_val_split_seed: 1
  noise:
    pressure_seed: 1
    pressure_std: 0
    velocity_seed: 2
    velocity_std: 0
  observe: both
  standardise: true
  test_length: 4
  train_length: 4
  val_length: 4
model_config:
  N_g: 0
  N_layers: 5
  N_neurons:
  - 96
  - 96
  - 96
  - 96
  - 96
  a: 0
  activations:
  - tanh
  - tanh
  - tanh
  - tanh
  - tanh
  dropout_rate: 0
  initializers:
  - glorot_uniform
  - glorot_uniform
  - glorot_uniform
  - glorot_uniform
  - glorot_uniform
  - glorot_uniform
  lambdas:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  model_path: figure_data/figure_5/model_2
  model_type: fnn
  regularizers:
  - None
  - None
  - None
  - None
  - None
  - None
  use_jump: false
  use_mean_flow: false
train_config:
  epochs: 500
  lambda_dd: 1
  lambda_e: 0
  lambda_m: 0
  learning_rate: 0.001
  learning_rate_schedule: constant
  sampled_batch_size: 0
  save_epochs:
  - 1
  - 10
  - 50
  - 100
  - 200
  - 300
  - 500
  - 800
  - 1000
  - 1500
  - 2000
  - 2500
  - 3000
  - 3500
  - 4000
  - 4500
  - 5000
  - 7500
  - 10000
