data_config:
  batch_size: 32
  data_path: data/Sim_Wave_G_Eqn_Sys_4_Sensor_5.mat
  data_type: kinematic
  dt: 0.0001
  interp_val_split: 0.2
  interp_val_split_seed: 1
  noise:
    pressure_seed: 1
    pressure_std: 10
    velocity_seed: 2
    velocity_std: 10
  observe: both
  standardise: false
  test_length: 4
  train_length: 4
  val_length: 4
model_config:
  N_g: 10
  N_layers: 1
  N_neurons:
  - 10
  a: 0
  activations:
  - harmonics
  dropout_rate: 0
  initializers:
  - periodic_uniform
  lambdas:
  - 0
  model_path: figure_data/figure_12/model_4
  model_type: gnn
  regularizers:
  - None
  use_jump: true
  use_mean_flow: true
train_config:
  epochs: 5000
  lambda_dd: 1
  lambda_e: 0.1
  lambda_m: 0.1
  learning_rate: 0.001
  learning_rate_schedule: exponential_decay
  sampled_batch_size: 512
  save_epochs:
  - 1
  - 10
  - 50
  - 100
  - 200
  - 300
  - 500
  - 800
  - 1000
  - 1500
  - 2000
  - 2500
  - 3000
  - 3500
  - 4000
  - 4500
  - 5000
